"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowLeft, Check, CheckCircle2, Clipboard, ExternalLink, PauseCircle, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import { api, ApiError } from "@/lib/api";
import { auditLabel, statusConfig, terminalStatuses } from "@/lib/status";
import { formatDate, formatMoney, formatScore, humanize, shortId } from "@/lib/formatters";
import type { AuditLog, EvaluationResponse, ExecutionResponse, IntegrationStatus, Intervention, RecoveryCase, ScoringResponse } from "@/types/recovery";
import { Button, Card, PageContainer, Skeleton, StatusBadge } from "@/components/ui";

type Busy = "score" | "evaluate" | "execute" | "simulate" | null;
function objectValue(value: unknown): Record<string, unknown> | null { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : null; }
function stringValue(value: unknown) { return typeof value === "string" ? value : null; }
function executionFrom(intervention?: Intervention): ExecutionResponse | null { const result = objectValue(intervention?.result_payload); const provider = objectValue(result?.provider); const message = objectValue(result?.message); if (!intervention || !provider || !message) return null; const url=stringValue(provider.short_url), id=stringValue(provider.payment_link_id), ref=stringValue(provider.reference_id), created=stringValue(provider.created_at); if(!url||!id||!ref||!created) return null; return { case_id:"", case_status:"CONTACTED", intervention_id:intervention.id, action_type:intervention.action_type, provider:stringValue(provider.name)??"Payment Link provider", mode:stringValue(provider.mode)??"unknown", idempotent_replay:true, payment_link:{payment_link_id:id,reference_id:ref,short_url:url,status:stringValue(provider.status)??"created",created_at:created}, message:{title:stringValue(message.title)??"Recovery payment",body:stringValue(message.body)??"",cta_label:stringValue(message.cta_label)??"Pay now",payment_url:stringValue(message.payment_url)??url,language:stringValue(message.language)??"en",source:stringValue(message.source)??"template"} }; }
function latestData(logs: AuditLog[], action: string) { return logs.filter(x=>x.action===action).at(-1)?.decision_data ?? null; }

export default function CaseDetailPage() {
  const params = useParams<{id:string}>(); const caseId=params.id;
  const [record,setRecord]=useState<RecoveryCase|null>(null); const [interventions,setInterventions]=useState<Intervention[]>([]); const [logs,setLogs]=useState<AuditLog[]>([]); const [integration,setIntegration]=useState<IntegrationStatus|null>(null); const [score,setScore]=useState<ScoringResponse|null>(null); const [evaluation,setEvaluation]=useState<EvaluationResponse|null>(null); const [execution,setExecution]=useState<ExecutionResponse|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [feedback,setFeedback]=useState<string|null>(null); const [busy,setBusy]=useState<Busy>(null); const [confirmExecute,setConfirmExecute]=useState(false); const [confirmCapture,setConfirmCapture]=useState(false); const lock=useRef(false);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const [item,items,timeline,provider]=await Promise.all([api.case(caseId),api.interventions(caseId),api.timeline(caseId),api.integration()]);setRecord(item);setInterventions(items);setLogs(timeline);setIntegration(provider);const restored=items.map(executionFrom).find(Boolean);if(restored)setExecution(restored);}catch(err){setError(err instanceof ApiError&&err.status===404?"Recovery case not found.":err instanceof Error?err.message:"The RecoverIQ backend is unavailable.");}finally{setLoading(false)}},[caseId]);
  useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  const mutate=async(kind:Exclude<Busy,null>,task:()=>Promise<unknown>,success:string)=>{if(lock.current)return;lock.current=true;setBusy(kind);setFeedback(null);try{const result=await task();if(kind==="score")setScore(result as ScoringResponse);if(kind==="evaluate")setEvaluation(result as EvaluationResponse);if(kind==="execute")setExecution(result as ExecutionResponse);setFeedback(success);await load();}catch(err){setFeedback(err instanceof Error?err.message:"The action could not be completed.");}finally{lock.current=false;setBusy(null);setConfirmExecute(false);setConfirmCapture(false)}};
  const pending=interventions.find(x=>!x.executed_at&&!x.cancelled_at); const executed=interventions.find(x=>x.executed_at); const blocked=record?terminalStatuses.includes(record.status)||record.experiment_group==="HOLDOUT":true; const policyData=latestData(logs,"POLICY_EVALUATED"); const decisionData=latestData(logs,"ACTION_SELECTED"); const scoreData=latestData(logs,"RECOVERY_SCORED"); const healthPolicyData=latestData(logs,"INTERVENTION_SUPPRESSED_METHOD_DEGRADED");
  const workflow=useMemo(()=>{if(!record)return[];const has=(a:string)=>logs.some(x=>x.action===a);const steps=[{name:"Detected",done:true},{name:"Diagnosed",done:record.status!=="DETECTED"},{name:"Scored",done:record.recoverability_score!=null},{name:"Policy checked",done:has("POLICY_EVALUATED")},{name:"Action scheduled",done:interventions.length>0},{name:"Contacted",done:!!executed},{name:"Recovered",done:record.status==="RECOVERED"}];const first=steps.findIndex(s=>!s.done);return steps.map((s,i)=>({...s,current:i===first,stopped:blocked&&!s.done}))},[record,logs,interventions,executed,blocked]);
  if(loading&&!record)return <PageContainer><div aria-label="Loading recovery case" className="space-y-5"><Skeleton className="h-12 w-1/2"/><Skeleton className="h-32"/><div className="grid gap-5 lg:grid-cols-2"><Skeleton className="h-64"/><Skeleton className="h-64"/></div></div></PageContainer>;
  if(error||!record)return <PageContainer><Link href="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-[#5b3ee4]"><ArrowLeft size={16}/>Dashboard</Link><Card><h1 className="text-xl font-bold">{error??"Recovery case not found."}</h1><p className="my-3 text-sm text-slate-600">Confirm that FastAPI is running and the case ID is valid.</p><Button onClick={()=>void load()}>Retry</Button></Card></PageContainer>;
  const stopCopy:Record<string,string>={HUMAN_REVIEW:"Automation paused for human review",SUPPRESSED:"Recovery action suppressed by policy",EXHAUSTED:"Recovery attempts exhausted"}; const scoreCategory=record.recoverability_score==null?null:record.recoverability_score>=.7?"High recovery potential":record.recoverability_score>=.4?"Medium recovery potential":"Low recovery potential"; const modeLabel=integration?.mode==="mock"?"Mock Mode":"Razorpay Test Mode";
  return <><header className="border-b border-[#e5e2dc] bg-white"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-4 px-4 py-4 sm:px-6 lg:px-10"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={17}/>Command Center</Link><div className="flex items-center gap-3"><span className="rounded-full bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-700">{modeLabel}</span><Button variant="secondary" disabled={loading} onClick={()=>void load()}><RefreshCw size={15} className={loading?"animate-spin":""}/>Refresh</Button></div></div></header><PageContainer>
  <div className="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-[#5b3ee4]">Recovery case</p><div className="mt-1 flex flex-wrap items-center gap-3"><h1 className="font-mono text-2xl font-bold sm:text-3xl" title={record.id}>{shortId(record.id)}</h1><StatusBadge status={record.status}/></div><p className="mt-2 text-sm text-slate-500">Opened {formatDate(record.opened_at)}</p></div><p className="text-3xl font-bold">{formatMoney(record.amount,record.currency)}</p></div>
  {feedback&&<div role="status" className="mb-5 rounded-xl border border-violet-200 bg-violet-50 px-4 py-3 text-sm text-violet-800">{feedback}</div>}{record.experiment_group&&<div className={`mb-5 rounded-xl border p-4 text-sm ${record.experiment_group==="HOLDOUT"?"border-slate-300 bg-slate-100":"border-violet-200 bg-violet-50"}`}><b>{humanize(record.experiment_group)}</b>{record.experiment_group==="HOLDOUT"&&<span> — no recovery intervention. Organic outcome only.</span>}</div>}{healthPolicyData&&<div className="mb-5 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900"><b>Payment Health policy applied.</b> {stringValue(healthPolicyData.reason)??"The original retry was suppressed because this payment method was degraded. An alternative payment method was recommended."}</div>}{stopCopy[record.status]&&<div className="mb-5 flex items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 font-semibold text-amber-900"><PauseCircle/>{stopCopy[record.status]}</div>}
  <Card><div className="mb-5"><h2 className="font-bold">Recovery workflow</h2><p className="mt-1 text-sm text-slate-500">A backend-confirmed journey from failure to captured payment</p></div><ol className="grid gap-3 sm:grid-cols-4 lg:grid-cols-7">{workflow.map((step,i)=><li key={step.name} className={`relative rounded-xl border p-3 ${step.done?"border-emerald-200 bg-emerald-50":step.current?"border-violet-300 bg-violet-50":"border-slate-200 bg-slate-50"}`}><span className={`mb-2 grid size-7 place-items-center rounded-full text-xs font-bold ${step.done?"bg-emerald-600 text-white":step.stopped?"bg-slate-300 text-slate-600":"bg-violet-100 text-violet-700"}`}>{step.done?<Check size={14}/>:i+1}</span><span className="text-xs font-semibold">{step.name}</span><span className="mt-1 block text-[11px] text-slate-500">{step.done?"Complete":step.current?"Current":step.stopped?"Blocked":"Pending"}</span></li>)}</ol></Card>
  <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><h2 className="font-bold">Case summary</h2><dl className="mt-5 grid grid-cols-2 gap-x-5 gap-y-4 text-sm">{[["Payment reference",record.payment_id??"—"],["Order reference",record.order_id??"—"],["Payment method",humanize(record.payment_method)],["Experiment group",humanize(record.experiment_group)],["Failure diagnosis",humanize(record.diagnosis)],["Current status",statusConfig[record.status].label],["Detected",formatDate(record.opened_at)],["Closed",formatDate(record.closed_at)]].map(([k,v])=><div key={k}><dt className="text-xs text-slate-500">{k}</dt><dd className="mt-1 break-all font-medium">{v}</dd></div>)}</dl></Card>
  <Card><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-[#5b3ee4]">Recoverability</p><h2 className="mt-1 text-xl font-bold">{scoreCategory??"Not calculated"}</h2></div><div className="grid size-16 place-items-center rounded-full border-4 border-violet-200 text-lg font-bold text-[#5b3ee4]">{record.recoverability_score==null?"—":formatScore(record.recoverability_score)}</div></div><p className="mt-4 text-sm text-slate-600">Source: {humanize(score?.source??stringValue(scoreData?.source)??"Not available")}</p>{(score?.explanation??(Array.isArray(scoreData?.explanation)?scoreData.explanation.filter((x):x is string=>typeof x==="string"):[])).length>0&&<ul className="mt-3 space-y-2 text-sm text-slate-600">{(score?.explanation??(scoreData?.explanation as string[])).map(x=><li key={x} className="flex gap-2"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-emerald-600"/>{x}</li>)}</ul>}{record.recoverability_score==null&&!blocked&&<Button className="mt-5 w-full" disabled={busy!==null} onClick={()=>void mutate("score",()=>api.score(record.id),"Recoverability score calculated.")}><Sparkles size={16}/>{busy==="score"?"Calculating…":"Calculate score"}</Button>}</Card></div>
  <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><h2 className="font-bold">Decision & policy</h2><div className="mt-4 rounded-xl bg-violet-50 p-4"><p className="text-xs font-semibold uppercase text-violet-700">Recommended by the recovery engine</p><p className="mt-1 text-lg font-bold">{humanize(evaluation?.decision.selected_action??stringValue(decisionData?.selected_action)??record.recommended_action)}</p>{evaluation?.decision.explanation.map(x=><p key={x} className="mt-2 text-sm text-slate-600">{x}</p>)}</div><div className="mt-3 rounded-xl bg-slate-50 p-4"><p className="flex items-center gap-2 text-xs font-semibold uppercase text-slate-600"><ShieldCheck size={15}/>Validated by deterministic merchant policies</p>{evaluation?<><p className={`mt-2 font-bold ${evaluation.policy.allowed?"text-emerald-700":"text-red-700"}`}>{evaluation.policy.allowed?"Approved":"Blocked"}</p><p className="mt-1 text-sm text-slate-600">{evaluation.policy.denial_reason??"All deterministic checks passed."}</p><div className="mt-3 flex flex-wrap gap-2">{Object.entries(evaluation.policy.checks).map(([k,v])=><span key={k} className={`rounded-full px-2 py-1 text-xs ${v?"bg-emerald-100 text-emerald-800":"bg-red-100 text-red-800"}`}>{humanize(k)}: {v?"Pass":"Fail"}</span>)}</div></>:policyData?<><p className={`mt-2 font-bold ${policyData.allowed?"text-emerald-700":"text-red-700"}`}>{policyData.allowed?"Approved":"Blocked"}</p><p className="mt-1 text-sm text-slate-600">{stringValue(policyData.denial_reason)??"Policy evaluation recorded in the audit trail."}</p></>:<p className="mt-2 text-sm text-slate-500">Not evaluated yet.</p>}</div>{record.recoverability_score!=null&&!policyData&&!evaluation&&!blocked&&<Button className="mt-5 w-full" disabled={busy!==null} onClick={()=>void mutate("evaluate",()=>api.evaluate(record.id),"Action evaluated against merchant policies.")}>{busy==="evaluate"?"Evaluating…":"Evaluate recovery action"}</Button>}{evaluation&&<p className="mt-3 text-xs text-slate-500">Expected recovery value: {formatMoney(evaluation.decision.expected_recovery_value,record.currency)}</p>}</Card>
  <Card><h2 className="font-bold">Intervention</h2>{record.status==="RECOVERED"?<div className="mt-4 rounded-xl bg-emerald-50 p-5"><CheckCircle2 className="text-emerald-600"/><h3 className="mt-3 text-lg font-bold text-emerald-900">Revenue recovered</h3><p className="mt-1 text-2xl font-bold text-emerald-800">{formatMoney(record.amount,record.currency)}</p><p className="mt-2 text-sm text-emerald-800">Captured-payment confirmation closed this case on {formatDate(record.closed_at)}. Pending actions were stopped.</p>{executed&&<p className="mt-2 text-xs text-emerald-700">Intervention: {humanize(executed.action_type)}</p>}</div>:pending?<><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-xs text-slate-500">Approved action</dt><dd className="mt-1 font-semibold">{humanize(pending.action_type)}</dd></div><div><dt className="text-xs text-slate-500">Scheduled</dt><dd className="mt-1 font-semibold">{formatDate(pending.scheduled_at)}</dd></div><div><dt className="text-xs text-slate-500">Provider</dt><dd className="mt-1 font-semibold">{modeLabel}</dd></div><div><dt className="text-xs text-slate-500">Execution</dt><dd className="mt-1 font-semibold">Pending</dd></div></dl>{!confirmExecute?<Button className="mt-5 w-full" disabled={busy!==null||blocked||!integration?.payment_link_execution_available} onClick={()=>setConfirmExecute(true)}>Execute recovery</Button>:<div role="dialog" aria-modal="true" aria-label="Confirm recovery execution" className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm text-amber-900">RecoverIQ will create a Payment Link and generate a message preview. No message will be sent automatically.</p><div className="mt-3 flex gap-2"><Button disabled={busy!==null} onClick={()=>void mutate("execute",()=>api.execute(pending.id),"Payment Link and message preview created.")}>{busy==="execute"?"Creating recovery link…":"Confirm execution"}</Button><Button variant="secondary" disabled={busy!==null} onClick={()=>setConfirmExecute(false)}>Cancel</Button></div></div>}</>:!executed?<p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No intervention has been scheduled for this case.</p>:null}
  {execution&&<div className="mt-5 border-t border-[#ebe8e2] pt-5"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold">Payment Link & message preview</h3><span className="rounded-full bg-violet-100 px-2.5 py-1 text-xs font-semibold text-violet-800">{modeLabel}{execution.idempotent_replay?" · Saved result":""}</span></div><p className="mt-3 break-all text-sm font-semibold text-[#5b3ee4]">{execution.payment_link.short_url}</p><p className="mt-1 text-xs text-slate-500">ID: {execution.payment_link.payment_link_id}</p><div className="mt-3 flex flex-wrap gap-2"><a href={execution.payment_link.short_url} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-[#5b3ee4] px-4 text-sm font-semibold text-white">Open payment link <ExternalLink size={14}/></a><Button variant="secondary" onClick={()=>void navigator.clipboard.writeText(execution.payment_link.short_url).then(()=>setFeedback("Payment Link copied."))}><Clipboard size={14}/>Copy link</Button></div><div className="mt-4 rounded-xl bg-[#faf9f7] p-4"><p className="font-bold">{execution.message.title}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{execution.message.body}</p><p className="mt-3 text-xs text-slate-500">CTA: {execution.message.cta_label} · Source: {humanize(execution.message.source)} · Created {formatDate(execution.payment_link.created_at)}</p></div><p className="mt-3 text-xs text-amber-700">Message preview only — RecoverIQ has not contacted the customer through an external channel. {integration?.mode==="mock"?"This is a demo Payment Link.":"This is Razorpay Test Mode, not a live link."}</p></div>}</Card></div>
  <Card className="mt-5"><h2 className="font-bold">Audit timeline</h2><p className="mt-1 text-sm text-slate-500">An append-only account of every system decision and state transition</p>{logs.length===0?<p className="mt-5 text-sm text-slate-500">No audit activity has been recorded.</p>:<ol className="mt-6 space-y-0">{logs.map((log,i)=><li key={log.id} className="relative flex gap-4 pb-6 last:pb-0"><div className="relative z-10 mt-1 size-3 shrink-0 rounded-full bg-[#5b3ee4] ring-4 ring-violet-100"/>{i<logs.length-1&&<div className="absolute left-[5px] top-4 h-full w-px bg-slate-200"/>}<div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{auditLabel(log.action)}</h3><span className="text-xs text-slate-400">{formatDate(log.created_at)}</span></div>{log.message&&<p className="mt-1 text-sm text-slate-600">{log.message}</p>}{log.previous_status&&log.new_status&&<p className="mt-1 text-xs text-slate-500">{statusConfig[log.previous_status].label} → {statusConfig[log.new_status].label}</p>}{stringValue(log.decision_data.denial_reason)&&<p className="mt-1 text-xs text-red-700">{stringValue(log.decision_data.denial_reason)}</p>}</div></li>)}</ol>}</Card>
  {(process.env.NODE_ENV!=="production"||process.env.NEXT_PUBLIC_DEMO_MODE==="true")&&record.payment_id&&<Card className="mt-5 border-dashed border-violet-300"><p className="text-xs font-bold uppercase tracking-wide text-violet-700">Demo controls</p><h2 className="mt-1 font-bold">Captured-payment simulator</h2><p className="mt-2 text-sm text-slate-600">Runs the existing backend webhook-processing path and only marks recovery after backend confirmation.</p>{record.status==="RECOVERED"?<p className="mt-4 text-sm font-semibold text-emerald-700">This case is already recovered.</p>:!confirmCapture?<Button className="mt-4" disabled={busy!==null} onClick={()=>setConfirmCapture(true)}>Simulate captured payment</Button>:<div role="dialog" aria-modal="true" aria-label="Confirm captured payment simulation" className="mt-4 rounded-xl bg-violet-50 p-4"><p className="text-sm">Confirm a simulated captured payment for {shortId(record.payment_id)}?</p><div className="mt-3 flex gap-2"><Button disabled={busy!==null} onClick={()=>void mutate("simulate",()=>api.simulateCaptured(record.payment_id!,record.order_id),"Captured payment confirmed. Case recovered.")}>{busy==="simulate"?"Confirming payment…":"Confirm capture"}</Button><Button variant="secondary" disabled={busy!==null} onClick={()=>setConfirmCapture(false)}>Cancel</Button></div></div>}</Card>}
  </PageContainer></>;
}
