export type RecoveryStatus = "DETECTED" | "DIAGNOSED" | "ACTION_SCHEDULED" | "CONTACTED" | "RECOVERED" | "EXHAUSTED" | "SUPPRESSED" | "HUMAN_REVIEW";
export type ExperimentGroup = "TREATMENT" | "HOLDOUT" | "INELIGIBLE";
export interface RecoveryCase { id: string; payment_id: string | null; order_id: string | null; payment_method: string | null; batch_id: string | null; experiment_group: ExperimentGroup | null; amount: number; currency: string; diagnosis: string | null; recoverability_score: number | null; recommended_action: string | null; status: RecoveryStatus; opened_at: string; updated_at: string; closed_at: string | null; }
export interface Overview { batch_id: string | null; total_cases: number; active_cases: number; eligible_cases: number; treatment_cases: number; holdout_cases: number; ineligible_cases: number; money_at_risk: number; initial_money_at_risk: number; recovered_amount: number; outstanding_amount: number; gross_recovery_rate: number | null; treatment_recovery_rate: number | null; holdout_recovery_rate: number | null; incremental_lift: number | null; average_recovery_time_seconds: number | null; interventions_attempted: number; suppressed_interventions: number; recovered_cases: number; treatment_recovered_cases: number; holdout_recovered_cases: number; }
export interface IntegrationStatus { mode: string; configured: boolean; payment_link_execution_available: boolean; }
export interface ScoringResponse { case_id: string; final_score: number; source: string; rule_score: number; ml_score: number | null; model_version: string | null; explanation: string[]; }
export interface Decision { selected_action: string; recoverability_score: number; expected_recovery_value: number; operational_cost: number; fatigue_penalty: number; risk_penalty: number; utility: number; explanation: string[]; candidate_actions: string[]; decision_version: string; }
export interface Policy { allowed: boolean; checks: Record<string, boolean>; denial_reason: string | null; resulting_status: RecoveryStatus; requires_human_review: boolean; policy_version: string; }
export interface Intervention { id: string; action_type: string; channel: string | null; action_payload: Record<string, unknown>; result_payload: Record<string, unknown> | null; scheduled_at: string | null; executed_at: string | null; cancelled_at: string | null; successful: boolean | null; cost: number | null; created_at: string; }
export interface EvaluationResponse { case_id: string; case_status: RecoveryStatus; recoverability_score: number; score_source: string; decision: Decision; policy: Policy; intervention: Intervention | null; }
export interface PaymentLink { payment_link_id: string; reference_id: string; short_url: string; status: string; created_at: string; }
export interface RecoveryMessage { title: string; body: string; cta_label: string; payment_url: string; language: string; source: string; }
export interface ExecutionResponse { case_id: string; case_status: RecoveryStatus; intervention_id: string; action_type: string; provider: string; mode: string; payment_link: PaymentLink; message: RecoveryMessage; idempotent_replay: boolean; }
export interface AuditLog { id: string; recovery_case_id: string; payment_event_id: string | null; action: string; actor: string; message: string | null; previous_status: RecoveryStatus | null; new_status: RecoveryStatus | null; decision_data: Record<string, unknown>; policy_checks: Record<string, unknown>; created_at: string; }
export interface SimulationResponse { payment_id: string; case_id: string; case_status: RecoveryStatus; }
export interface DemoBatchRequest { seed: number; batch_size: number; treatment_percent: number; idempotency_key: string; }
export interface DemoBatchResponse { batch_id: string; seed: number; requested_cases: number; created_cases: number; treatment_cases: number; holdout_cases: number; ineligible_cases: number; recovered_cases: number; interventions_attempted: number; suppressed_interventions: number; status: string; simulated: boolean; metrics: Overview; idempotent_replay: boolean; }
export type PaymentHealthStatus = "HEALTHY" | "DEGRADED" | "INSUFFICIENT_DATA" | "NO_BASELINE";
export interface PaymentMethodHealth { payment_method: string; status: PaymentHealthStatus; total_attempts: number; failed_attempts: number; observed_failure_rate: number | null; baseline_failure_rate: number | null; threshold: number; degradation_limit: number | null; recommended_action: string | null; reminders_suppressed: boolean; reason: string; }
export interface PaymentHealthResponse { batch_id: string | null; window_start: string | null; window_end: string | null; overall_status: string; degraded_methods: string[]; methods: PaymentMethodHealth[]; generated_at: string; simulated: boolean; }
