"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, CircleDollarSign, RefreshCw, Search, ShieldCheck, TrendingUp, WalletCards } from "lucide-react";
import { api } from "@/lib/api";
import { formatDate, formatMoney, formatScore, humanize, shortId } from "@/lib/formatters";
import { attentionRank, terminalStatuses } from "@/lib/status";
import type { IntegrationStatus, Overview, RecoveryCase, RecoveryStatus } from "@/types/recovery";
import { Button, Card, PageContainer, Skeleton, StatusBadge } from "@/components/ui";

type Filter = "all" | "active" | "recovered" | "review";

export default function DashboardPage() {
  const [overview, setOverview] = useState<Overview | null>(null); const [cases, setCases] = useState<RecoveryCase[]>([]); const [integration, setIntegration] = useState<IntegrationStatus | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [filter, setFilter] = useState<Filter>("all"); const [query, setQuery] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [metrics, records, provider] = await Promise.all([api.overview(), api.cases(), api.integration()]); setOverview(metrics); setCases(records); setIntegration(provider); } catch (err) { setError(err instanceof Error ? err.message : "RecoverIQ could not reach the backend."); } finally { setLoading(false); } }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const visible = useMemo(() => cases.filter((item) => filter === "all" || (filter === "active" && !terminalStatuses.includes(item.status)) || (filter === "recovered" && item.status === "RECOVERED") || (filter === "review" && item.status === "HUMAN_REVIEW")).filter((item) => !query || [item.id, item.payment_id, item.diagnosis, item.recommended_action].some((value) => value?.toLowerCase().includes(query.toLowerCase()))).sort((a, b) => attentionRank[a.status] - attentionRank[b.status] || b.amount - a.amount || +new Date(b.opened_at) - +new Date(a.opened_at)), [cases, filter, query]);
  const statusCounts = (status: RecoveryStatus[]) => cases.filter((item) => status.includes(item.status)).length;
  const recoveryRate = overview?.total_cases ? overview.recovered_cases / overview.total_cases : 0;

  return <><header className="border-b border-[#e5e2dc] bg-white"><div className="mx-auto flex max-w-[1440px] flex-col gap-4 px-4 py-5 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-10"><div><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-[#5b3ee4] text-white"><TrendingUp size={19}/></span><h1 className="text-xl font-bold tracking-tight">RecoverIQ</h1></div><p className="mt-1 text-sm text-slate-500">AI-assisted, policy-controlled revenue recovery</p></div><div className="flex flex-wrap items-center gap-3"><span className={`flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-semibold ${error ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}><span className={`size-2 rounded-full ${error ? "bg-red-500" : "bg-emerald-500"}`}/>{error ? "Backend offline" : "Backend connected"}</span>{integration && <span className="rounded-full bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-700">{integration.mode === "mock" ? "Mock Mode" : "Razorpay Test Mode"}</span>}<Button variant="secondary" onClick={() => void load()} disabled={loading}><RefreshCw size={15} className={loading ? "animate-spin" : ""}/>Refresh</Button></div></div></header>
  <PageContainer><div className="mb-7"><p className="text-sm font-semibold text-[#5b3ee4]">Revenue Recovery Command Center</p><h2 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Recover more. Risk less.</h2><p className="mt-2 max-w-2xl text-slate-600">Monitor failed payments, policy decisions, and recovered revenue from one operational view.</p></div>
  {error ? <Card className="border-red-200"><div className="flex flex-col items-start gap-3"><div className="rounded-full bg-red-50 p-3 text-red-600"><Activity/></div><h3 className="text-lg font-bold">The RecoverIQ backend is unavailable</h3><p className="text-sm text-slate-600">{error} Confirm that FastAPI is running and try again.</p><Button onClick={() => void load()}>Retry connection</Button></div></Card> : <>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{loading ? Array.from({length:4}).map((_,i)=><Card key={i}><Skeleton className="mb-5 size-10"/><Skeleton className="mb-2 h-8 w-32"/><Skeleton className="h-4 w-44"/></Card>) : [
    ["Revenue at risk", formatMoney(overview?.money_at_risk ?? 0), "Open failed-payment value", WalletCards], ["Revenue recovered", formatMoney(overview?.recovered_amount ?? 0), "Confirmed captured payments", CircleDollarSign], ["Active recovery cases", String(overview?.active_cases ?? 0), "Cases requiring action", Activity], ["Recovery rate", `${Math.round(recoveryRate*100)}%`, "Recovered cases / all cases", ShieldCheck]
  ].map(([label,value,note,Icon]) => { const MetricIcon = Icon as typeof Activity; return <Card key={String(label)}><div className="mb-5 flex size-10 items-center justify-center rounded-xl bg-violet-50 text-[#5b3ee4]"><MetricIcon size={19}/></div><p className="text-2xl font-bold">{String(value)}</p><h3 className="mt-1 text-sm font-semibold">{String(label)}</h3><p className="mt-1 text-xs text-slate-500">{String(note)}</p></Card>; })}</div>
  <Card className="mt-5"><div className="mb-5 flex items-end justify-between"><div><h3 className="font-bold">Recovery workflow</h3><p className="mt-1 text-sm text-slate-500">Live case distribution across meaningful stages</p></div><span className="text-sm font-semibold text-slate-500">{cases.length} total</span></div><div className="grid gap-3 sm:grid-cols-5">{[["Detected / Diagnosed", statusCounts(["DETECTED","DIAGNOSED"]),"bg-violet-500"],["Action scheduled",statusCounts(["ACTION_SCHEDULED"]),"bg-amber-500"],["Contacted",statusCounts(["CONTACTED"]),"bg-blue-500"],["Recovered",statusCounts(["RECOVERED"]),"bg-emerald-500"],["Human review",statusCounts(["HUMAN_REVIEW"]),"bg-red-500"]].map(([label,count,color])=><div key={String(label)} className="rounded-xl bg-[#faf9f7] p-4"><div className="flex items-center justify-between gap-2"><span className="text-xs font-medium text-slate-600">{label}</span><b>{count}</b></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className={`h-full rounded-full ${color}`} style={{width: cases.length ? `${Math.max(8, Number(count)/cases.length*100)}%` : "0%"}}/></div></div>)}</div></Card>
  <Card className="mt-5 !p-0 overflow-hidden"><div className="flex flex-col gap-4 border-b border-[#ebe8e2] p-5 lg:flex-row lg:items-center lg:justify-between"><div><h3 className="font-bold">Recovery cases</h3><p className="mt-1 text-sm text-slate-500">Prioritized by attention, value, and recency</p></div><div className="flex flex-col gap-3 sm:flex-row"><div className="flex rounded-lg bg-[#f2f0ec] p-1">{(["all","active","recovered","review"] as Filter[]).map(item=><button key={item} onClick={()=>setFilter(item)} className={`rounded-md px-3 py-1.5 text-xs font-semibold capitalize ${filter===item ? "bg-white shadow-sm" : "text-slate-500"}`}>{item}</button>)}</div><label className="flex items-center gap-2 rounded-lg border border-[#ddd8cf] bg-white px-3"><Search size={15} className="text-slate-400"/><span className="sr-only">Search cases</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cases" className="h-10 w-full bg-transparent text-sm outline-none sm:w-40"/></label></div></div>
  {loading ? <div className="space-y-4 p-5" aria-label="Loading recovery cases">{Array.from({length:5}).map((_,i)=><Skeleton key={i} className="h-12"/>)}</div> : visible.length===0 ? <div className="p-12 text-center"><h4 className="font-bold">No recovery cases yet</h4><p className="mt-2 text-sm text-slate-500">Trigger a failed payment event to see RecoverIQ diagnose and process it.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-[#faf9f7] text-xs uppercase tracking-wide text-slate-500"><tr>{["Case","Amount","Diagnosis","Score","Recommendation","Status","Created",""] .map(x=><th key={x} className="px-5 py-3 font-semibold">{x}</th>)}</tr></thead><tbody className="divide-y divide-[#efede8]">{visible.map(item=><tr key={item.id} className="hover:bg-violet-50/40"><td className="px-5 py-4 font-mono text-xs" title={item.id}>{shortId(item.id)}</td><td className="px-5 py-4 font-semibold">{formatMoney(item.amount,item.currency)}</td><td className="max-w-52 truncate px-5 py-4 text-slate-600">{humanize(item.diagnosis)}</td><td className="px-5 py-4 font-semibold">{formatScore(item.recoverability_score)}</td><td className="px-5 py-4 text-slate-600">{humanize(item.recommended_action)}</td><td className="px-5 py-4"><StatusBadge status={item.status}/></td><td className="px-5 py-4 text-slate-500">{formatDate(item.opened_at)}</td><td className="px-5 py-4"><Link aria-label={`View case ${item.id}`} href={`/cases/${item.id}`} className="inline-flex items-center gap-1 font-semibold text-[#5b3ee4]">View <ArrowRight size={14}/></Link></td></tr>)}</tbody></table></div>}</Card></>}</PageContainer></>;
}
