"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, RefreshCw, Search, TrendingUp } from "lucide-react";
import { ExperimentPanel } from "@/components/dashboard/experiment-panel";
import { Button, Card, PageContainer, Skeleton, StatusBadge } from "@/components/ui";
import { api } from "@/lib/api";
import { formatDate, formatMoney, formatScore, humanize, shortId } from "@/lib/formatters";
import { attentionRank, terminalStatuses } from "@/lib/status";
import type { IntegrationStatus, Overview, PaymentHealthResponse, RecoveryCase, RecoveryStatus } from "@/types/recovery";

type Filter = "all" | "treatment" | "holdout" | "active" | "recovered" | "review";

export default function DashboardPage() {
  const [overview,setOverview]=useState<Overview|null>(null); const [cases,setCases]=useState<RecoveryCase[]>([]); const [health,setHealth]=useState<PaymentHealthResponse|null>(null); const [integration,setIntegration]=useState<IntegrationStatus|null>(null); const [batchId,setBatchId]=useState<string|null>(null); const [batchKey,setBatchKey]=useState<string|null>(null); const [running,setRunning]=useState(false); const [batchError,setBatchError]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [filter,setFilter]=useState<Filter>("all"); const [search,setSearch]=useState("");
  const load=useCallback(async(scope?:string|null)=>{setLoading(true);setError(null);const selected=scope===undefined?sessionStorage.getItem("recoveriq_batch_id"):scope;try{const [metrics,records,paymentHealth,provider]=await Promise.all([api.overview(selected),api.cases(selected),api.paymentHealth(selected),api.integration()]);setOverview(metrics);setCases(records);setHealth(paymentHealth);setIntegration(provider);}catch(err){setError(err instanceof Error?err.message:"RecoverIQ could not reach the backend.");}finally{setLoading(false)}},[]);
  useEffect(()=>{queueMicrotask(()=>{const saved=sessionStorage.getItem("recoveriq_batch_id");setBatchId(saved);void load(saved)})},[load]);
  const runBatch=async()=>{if(running)return;const key=batchKey??crypto.randomUUID();setBatchKey(key);setRunning(true);setBatchError(null);try{const result=await api.runDemoBatch({seed:42,batch_size:100,treatment_percent:80,idempotency_key:key});setBatchId(result.batch_id);sessionStorage.setItem("recoveriq_batch_id",result.batch_id);await load(result.batch_id);setBatchKey(null);}catch(err){setBatchError(err instanceof Error?err.message:"The demo batch could not be completed. Retry using the same request to avoid duplicate cases.");}finally{setRunning(false)}};
  const visible=useMemo(()=>cases.filter(item=>filter==="all"||(filter==="treatment"&&item.experiment_group==="TREATMENT")||(filter==="holdout"&&item.experiment_group==="HOLDOUT")||(filter==="active"&&!terminalStatuses.includes(item.status))||(filter==="recovered"&&item.status==="RECOVERED")||(filter==="review"&&item.status==="HUMAN_REVIEW")).filter(item=>!search||[item.id,item.payment_id,item.payment_method,item.diagnosis,item.recommended_action].some(value=>value?.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>attentionRank[a.status]-attentionRank[b.status]||b.amount-a.amount),[cases,filter,search]);
  const count=(statuses:RecoveryStatus[])=>cases.filter(item=>statuses.includes(item.status)).length;
  return <><header className="border-b border-[#e5e2dc] bg-white"><div className="mx-auto flex max-w-[1440px] flex-col gap-4 px-4 py-5 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-10"><div><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-[#5b3ee4] text-white"><TrendingUp size={19}/></span><h1 className="text-xl font-bold">RecoverIQ</h1></div><p className="mt-1 text-sm text-slate-500">AI-assisted, policy-controlled revenue recovery</p></div><div className="flex flex-wrap items-center gap-3"><span className={`flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-semibold ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}><span className={`size-2 rounded-full ${error?"bg-red-500":"bg-emerald-500"}`}/>{error?"Backend offline":"Backend connected"}</span>{integration&&<span className="rounded-full bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-700">{integration.mode==="mock"?"Mock Mode":"Razorpay Test Mode"}</span>}<Button variant="secondary" onClick={()=>void load(batchId)} disabled={loading}><RefreshCw size={15} className={loading?"animate-spin":""}/>Refresh</Button></div></div></header>
  <PageContainer><div className="mb-7"><p className="text-sm font-semibold text-[#5b3ee4]">Revenue Recovery Command Center</p><h2 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Recover more. Risk less.</h2><p className="mt-2 text-slate-600">Measure intervention lift and payment-method health from real backend data.</p></div>
  {error?<Card className="border-red-200"><Activity className="text-red-600"/><h2 className="mt-3 text-lg font-bold">RecoverIQ could not reach the backend</h2><p className="mt-2 text-sm text-slate-600">{error} Confirm that FastAPI is running and try again.</p><Button className="mt-4" onClick={()=>void load(batchId)}>Retry connection</Button></Card>:<><ExperimentPanel batchId={batchId} metrics={overview} health={health} loading={loading} running={running} error={batchError} onRun={()=>void runBatch()}/>
  <Card className="mt-5"><div className="mb-5 flex items-end justify-between"><div><h3 className="font-bold">Recovery workflow</h3><p className="mt-1 text-sm text-slate-500">Live case distribution for {batchId?"the selected simulated batch":"all cases"}</p></div><span className="text-sm font-semibold text-slate-500">{cases.length} total</span></div><div className="grid gap-3 sm:grid-cols-5">{[["Detected / Diagnosed",count(["DETECTED","DIAGNOSED"]),"bg-violet-500"],["Action scheduled",count(["ACTION_SCHEDULED"]),"bg-amber-500"],["Contacted",count(["CONTACTED"]),"bg-blue-500"],["Recovered",count(["RECOVERED"]),"bg-emerald-500"],["Human review",count(["HUMAN_REVIEW"]),"bg-red-500"]].map(([label,value,color])=><div key={String(label)} className="rounded-xl bg-[#faf9f7] p-4"><div className="flex justify-between gap-2"><span className="text-xs text-slate-600">{label}</span><b>{value}</b></div><div className="mt-3 h-1.5 rounded-full bg-slate-200"><div className={`h-full rounded-full ${color}`} style={{width:cases.length?`${Math.max(8,Number(value)/cases.length*100)}%`:"0%"}}/></div></div>)}</div></Card>
  <Card className="mt-5 !overflow-hidden !p-0"><div className="flex flex-col gap-4 border-b border-[#ebe8e2] p-5 lg:flex-row lg:items-center lg:justify-between"><div><h3 className="font-bold">Recovery cases</h3><p className="mt-1 text-sm text-slate-500">Treatment and holdout cases remain visibly distinct</p></div><div className="flex flex-col gap-3 sm:flex-row"><div className="flex flex-wrap rounded-lg bg-[#f2f0ec] p-1">{(["all","treatment","holdout","active","recovered","review"] as Filter[]).map(item=><button key={item} onClick={()=>setFilter(item)} className={`rounded-md px-3 py-1.5 text-xs font-semibold capitalize ${filter===item?"bg-white shadow-sm":"text-slate-500"}`}>{item}</button>)}</div><label className="flex items-center gap-2 rounded-lg border border-[#ddd8cf] px-3"><Search size={15}/><span className="sr-only">Search cases</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search cases" className="h-10 w-full bg-transparent text-sm outline-none sm:w-40"/></label></div></div>
  {loading?<div aria-label="Loading recovery cases" className="space-y-4 p-5">{Array.from({length:5}).map((_,i)=><Skeleton key={i} className="h-12"/>)}</div>:visible.length===0?<div className="p-12 text-center"><h4 className="font-bold">No recovery cases were found for this batch</h4><p className="mt-2 text-sm text-slate-500">Run a demo batch or choose another filter.</p></div>:<div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-[#faf9f7] text-xs uppercase text-slate-500"><tr>{["Case","Amount","Method","Experiment","Diagnosis","Score","Recommendation","Status","Created",""] .map(label=><th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-[#efede8]">{visible.map(item=><tr key={item.id} className="hover:bg-violet-50/40"><td className="px-4 py-4 font-mono text-xs" title={item.id}>{shortId(item.id)}</td><td className="px-4 py-4 font-semibold">{formatMoney(item.amount,item.currency)}</td><td className="px-4 py-4">{humanize(item.payment_method)}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.experiment_group==="TREATMENT"?"bg-violet-100 text-violet-800":item.experiment_group==="HOLDOUT"?"bg-slate-200 text-slate-700":"bg-amber-100 text-amber-800"}`}>{item.experiment_group==="HOLDOUT"?"Holdout — no intervention":humanize(item.experiment_group)}</span></td><td className="max-w-52 truncate px-4 py-4">{humanize(item.diagnosis)}</td><td className="px-4 py-4 font-semibold">{formatScore(item.recoverability_score)}</td><td className="px-4 py-4">{item.experiment_group==="HOLDOUT"?"No intervention":humanize(item.recommended_action)}</td><td className="px-4 py-4"><StatusBadge status={item.status}/></td><td className="px-4 py-4 text-slate-500">{formatDate(item.opened_at)}</td><td className="px-4 py-4"><Link href={`/cases/${item.id}`} className="inline-flex items-center gap-1 font-semibold text-[#5b3ee4]">View <ArrowRight size={14}/></Link></td></tr>)}</tbody></table></div>}</Card></>}</PageContainer></>;
}
