"""create initial RecoverIQ tables

Revision ID: bd7ef6f65355
Revises: 
Create Date: 2026-08-28 11:06:22.693320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7ef6f65355'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('recoverability_score', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DETECTED', 'DIAGNOSED', 'ACTION_SCHEDULED', 'CONTACTED', 'RECOVERED', 'EXHAUSTED', 'SUPPRESSED', 'HUMAN_REVIEW', name='recovery_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_recovery_cases_amount_nonnegative'),
    sa.CheckConstraint('recoverability_score IS NULL OR (recoverability_score >= 0 AND recoverability_score <= 1)', name='ck_recovery_cases_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_order_id'), 'recovery_cases', ['order_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_payment_id'), 'recovery_cases', ['payment_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_status'), 'recovery_cases', ['status'], unique=False)
    op.create_index('ix_recovery_cases_status_updated_at', 'recovery_cases', ['status', 'updated_at'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recovery_case_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('action_payload', sa.JSON(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name='ck_interventions_cost_nonnegative'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interventions_case_scheduled_at', 'interventions', ['recovery_case_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_interventions_recovery_case_id'), 'interventions', ['recovery_case_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_source', sa.String(length=100), nullable=True),
    sa.Column('error_step', sa.String(length=100), nullable=True),
    sa.Column('error_reason', sa.String(length=150), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('normalized_payload', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recovery_case_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name='ck_payment_events_amount_nonnegative'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_event_id'), 'payment_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_payment_events_event_type'), 'payment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_events_order_id'), 'payment_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    op.create_index('ix_payment_events_payment_occurred', 'payment_events', ['payment_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_payment_events_recovery_case_id'), 'payment_events', ['recovery_case_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recovery_case_id', sa.String(length=36), nullable=False),
    sa.Column('payment_event_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('previous_status', sa.Enum('DETECTED', 'DIAGNOSED', 'ACTION_SCHEDULED', 'CONTACTED', 'RECOVERED', 'EXHAUSTED', 'SUPPRESSED', 'HUMAN_REVIEW', name='ck_audit_logs_previous_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('new_status', sa.Enum('DETECTED', 'DIAGNOSED', 'ACTION_SCHEDULED', 'CONTACTED', 'RECOVERED', 'EXHAUSTED', 'SUPPRESSED', 'HUMAN_REVIEW', name='ck_audit_logs_new_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('decision_data', sa.JSON(), nullable=False),
    sa.Column('policy_checks', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_event_id'], ['payment_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_case_created_at', 'audit_logs', ['recovery_case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_payment_event_id'), 'audit_logs', ['payment_event_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_recovery_case_id'), 'audit_logs', ['recovery_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_recovery_case_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_payment_event_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_case_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_payment_events_recovery_case_id'), table_name='payment_events')
    op.drop_index('ix_payment_events_payment_occurred', table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_order_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_type'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_interventions_recovery_case_id'), table_name='interventions')
    op.drop_index('ix_interventions_case_scheduled_at', table_name='interventions')
    op.drop_table('interventions')
    op.drop_index('ix_recovery_cases_status_updated_at', table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_payment_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_order_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    # ### end Alembic commands ###
